# Generated by Django 4.2.3 on 2023-07-28 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapproval',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
