# Generated by Django 4.2.3 on 2023-07-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
    ]
