# Generated by Django 4.2.3 on 2023-07-28 05:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('loan_days_term', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'loan_approvals',
            },
        ),
        migrations.RemoveField(
            model_name='loan',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_days_term',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='loan',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loans',
        ),
        migrations.AddField(
            model_name='loan',
            name='approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loanapproval'),
        ),
    ]
