# Generated by Django 4.2.3 on 2023-07-28 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userapproval_credit_history'),
        ('loan', '0002_loanapproval_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapproval',
            name='rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='loanapproval',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loanapproval')),
            ],
            options={
                'db_table': 'loan_histories',
            },
        ),
        migrations.CreateModel(
            name='LoanApprovalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('loan_days_term', models.IntegerField()),
                ('receiverAccountNo', models.TextField()),
                ('is_approved', models.BooleanField(null=True)),
                ('rate', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'loan_approval_histories',
            },
        ),
    ]
