# Generated by Django 4.2.3 on 2023-07-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_created_at_loanhistory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanhistory',
            name='approval',
        ),
        migrations.AddField(
            model_name='loanapproval',
            name='is_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoanApprovalHistory',
        ),
        migrations.DeleteModel(
            name='LoanHistory',
        ),
    ]
