# Generated by Django 4.2.3 on 2023-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_remove_loanhistory_approval_loanapproval_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapproval',
            name='is_done',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
