# Generated by Django 4.2.3 on 2023-07-28 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only digits are allowed.')])),
                ('role', models.TextField(default='USER')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
