# Generated by Django 4.2.3 on 2023-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapproval',
            name='credit_history',
            field=models.IntegerField(default=1),
        ),
    ]
