# Generated by Django 4.2.3 on 2023-07-28 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_userapproval_credit_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'forgot_password_links',
            },
        ),
    ]
